#iPhoneProductId is added with the value- 6960ea76c941646b7a8b3dd5
#Wed Aug 19 17:23:21 IST 2026
iPhoneProductId=6960ea76c941646b7a8b3dd5
token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTg1NmUzNjIxMDU0YmE0NjVlMGMxMjIiLCJ1c2VyRW1haWwiOiJ5YXNlcjFAeWFzZXIxLmNvbSIsInVzZXJNb2JpbGUiOjk4NzY1NDMyMTAsInVzZXJSb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3ODcxMzc3MzQsImV4cCI6MTgxODY5NTMzNH0.4T2ZVN4M4aybpYhFG8VIDU1xZvDp9VLdteWeFbQ-iFI
userId=6a856e3621054ba465e0c122
